import { ExtractedDocumentData, VerifiedCircularityRecord, AuditScenario } from "@/types";

export const CLEAN_DOCUMENTS: ExtractedDocumentData[] = [
  {
    id: "doc-clean-01",
    documentType: "waste_invoice",
    fileName: "INV-2026-TIR-8842_SriLakshmi_Waste_Dispatch.pdf",
    fileSize: "1.4 MB",
    uploadTimestamp: "2026-08-20T09:15:00Z",
    issuer: "Sri Lakshmi Garment Mills Ltd, Tirupur, India",
    targetParty: "EcoSpin Reclaimers Pvt Ltd, Coimbatore",
    referenceNumber: "INV-2026-8842",
    materialName: "Pre-consumer Combed Cotton/Poly Cutting Waste",
    quantityKg: 10000,
    composition: {
      cottonPercentage: 78.4,
      polyesterPercentage: 21.6,
      fiberDescription: "Knitting Clip Scrap (100% Pre-Consumer)",
    },
    gsm: 220,
    source: "pre-consumer",
    dispatchDate: "2026-08-20",
    location: "Tirupur, Tamil Nadu, India",
    confidence: 0.98,
    extractedFields: {
      invoiceNumber: { value: "INV-2026-8842", confidence: 0.99, label: "Invoice Number" },
      grossQuantity: { value: "10,000 kg", confidence: 0.98, label: "Billed Quantity" },
      materialGrade: { value: "Grade A Combed Waste", confidence: 0.96, label: "Material Grade" },
      dispatchLocation: { value: "Tirupur Facility 4", confidence: 0.97, label: "Dispatch Hub" },
    },
    rawTextSnippet: "SRI LAKSHMI GARMENT MILLS LTD\nTax Invoice: INV-2026-8842\nConsignee: EcoSpin Reclaimers Coimbatore\nDescription: 10,000 KG Pre-consumer Cotton/Poly Scrap\nDeclared Weight: 10,000.00 KG\nFiber Ratio: 78.4% Cotton / 21.6% PET\nDate: 20-Aug-2026",
  },
  {
    id: "doc-clean-02",
    documentType: "weighbridge_slip",
    fileName: "WB-SLIP-99014_Coimbatore_Weighbridge.pdf",
    fileSize: "890 KB",
    uploadTimestamp: "2026-08-20T14:30:00Z",
    issuer: "Coimbatore Integrated Logistics Weighbridge Hub",
    targetParty: "EcoSpin Reclaimers Pvt Ltd",
    referenceNumber: "WB-99014",
    materialName: "Textile Scrap in Bales",
    quantityKg: 9920,
    composition: {
      cottonPercentage: 78.4,
      polyesterPercentage: 21.6,
      fiberDescription: "Baled Waste Scrap (Inbound Net)",
    },
    source: "post-industrial",
    receiveDate: "2026-08-20",
    location: "Coimbatore Inbound Terminal",
    confidence: 0.99,
    extractedFields: {
      grossWeight: { value: "24,820 kg", confidence: 0.99, label: "Gross Truck Weight" },
      tareWeight: { value: "14,900 kg", confidence: 0.99, label: "Tare Truck Weight" },
      netWeight: { value: "9,920 kg", confidence: 0.99, label: "Net Received Weight" },
      transitVariance: { value: "80 kg (0.80% - Normal moisture & transit loss)", confidence: 0.95, label: "Inbound Variance" },
    },
    rawTextSnippet: "COIMBATORE WEIGHBRIDGE HUB\nSlip ID: WB-99014\nTruck No: TN-38-BZ-4419\nGross: 24,820 KG | Tare: 14,900 KG | NET RECEIVED: 9,920 KG\nMoisture / Handling variance: -80 KG (within 1% tolerance threshold)",
  },
  {
    id: "doc-clean-03",
    documentType: "lab_report",
    fileName: "SGS_Lab_Spec_Verification_RPT-7712.pdf",
    fileSize: "2.1 MB",
    uploadTimestamp: "2026-08-21T11:00:00Z",
    issuer: "SGS Textile Quality Laboratories",
    targetParty: "EcoSpin Reclaimers Pvt Ltd",
    referenceNumber: "SGS-IND-7712-Q",
    materialName: "De-fibered Recycled Cotton Blend",
    quantityKg: 9920,
    composition: {
      cottonPercentage: 78.4,
      polyesterPercentage: 21.6,
      fiberDescription: "Standard Mechanical Garnetted Recycled Blend",
    },
    gsm: 220,
    yarnCount: "Ne 24s/1 Recycled",
    source: "pre-consumer",
    confidence: 0.97,
    extractedFields: {
      fiberTestCotton: { value: "78.4% (AATCC 20A)", confidence: 0.99, label: "Cotton Fraction" },
      fiberTestPoly: { value: "21.6% (AATCC 20A)", confidence: 0.99, label: "Polyester Fraction" },
      gsmTest: { value: "220 g/m² (ISO 3801)", confidence: 0.98, label: "Measured GSM" },
      harmfulSubstances: { value: "None Detected (Pass OEKO-TEX Std 100)", confidence: 0.96, label: "Chemical Safety" },
      tensileStrength: { value: "18.4 cN/tex (Satisfactory)", confidence: 0.94, label: "Fiber Tenacity" },
    },
    rawTextSnippet: "SGS TEXTILE QUALITY TESTING REPORT\nRef: SGS-IND-7712-Q\nSample: Recycled Cotton Blend Lot #TX-000184\nQuantitative Blend Analysis: 78.4% Cotton, 21.6% Polyester.\nHeavy Metals: Undetected. Formaldehyde: <10 ppm. PASS.",
  },
  {
    id: "doc-clean-04",
    documentType: "recycling_certificate",
    fileName: "ControlUnion_RCS_Certificate_CU881920.pdf",
    fileSize: "1.8 MB",
    uploadTimestamp: "2026-08-21T16:00:00Z",
    issuer: "Control Union Certifications B.V.",
    targetParty: "EcoSpin Reclaimers Pvt Ltd",
    referenceNumber: "CU-RCS-2026-881920",
    materialName: "Recycled Claim Standard (RCS) Scope Certificate",
    quantityKg: 500000,
    composition: {
      cottonPercentage: 78.4,
      polyesterPercentage: 21.6,
      fiberDescription: "Pre-consumer & Post-industrial Textile Waste",
    },
    source: "pre-consumer",
    certification: {
      standard: "RCS",
      certificateNumber: "CU-881920-RCS-2026-01",
      validFrom: "2026-01-01",
      validUntil: "2026-12-31",
      status: "Valid",
    },
    confidence: 0.99,
    extractedFields: {
      certStandard: { value: "RCS v2.0 (Recycled Claim Standard)", confidence: 0.99, label: "Certification Standard" },
      certStatus: { value: "Active / Validated (Expires Dec 31, 2026)", confidence: 0.99, label: "Validity Status" },
      facilityAudited: { value: "EcoSpin Processing Facility 2 Coimbatore", confidence: 0.98, label: "Certified Facility" },
    },
    rawTextSnippet: "CONTROL UNION CERTIFICATIONS\nScope Certificate: CU-881920-RCS-2026-01\nLicensee: EcoSpin Reclaimers Pvt Ltd\nProducts: Mechanically Recycled Cotton / Recycled Polyester\nValid: 01-Jan-2026 to 31-Dec-2026. Status: ACTIVE.",
  },
  {
    id: "doc-clean-05",
    documentType: "grn",
    fileName: "GRN-2026-APEX-4109_Recycled_Yarn_Production.pdf",
    fileSize: "1.2 MB",
    uploadTimestamp: "2026-08-22T17:45:00Z",
    issuer: "Apex Recycled Yarns Ltd, Erode",
    targetParty: "Nordic EcoWear Global / Aura Knits",
    referenceNumber: "GRN-APX-4109",
    materialName: "Ne 24s Carded Recycled Cotton/Poly Ring Spun Yarn",
    quantityKg: 8200,
    composition: {
      cottonPercentage: 78.4,
      polyesterPercentage: 21.6,
      fiberDescription: "RCS Blended Certified Yarn",
    },
    yarnCount: "Ne 24/1",
    source: "pre-consumer",
    dispatchDate: "2026-08-22",
    location: "Erode Spinning Mill Unit 1",
    confidence: 0.98,
    extractedFields: {
      producedYarnKg: { value: "8,200 kg", confidence: 0.99, label: "Verified Recycled Output" },
      processingLossKg: { value: "1,720 kg (17.34% Comber Noil + Short Fiber Fall)", confidence: 0.97, label: "Calculated Processing Loss" },
      recoveryRate: { value: "82.66% (Standard mechanical spinning recovery)", confidence: 0.98, label: "Mass Balance Recovery Rate" },
    },
    rawTextSnippet: "APEX RECYCLED YARNS LTD\nGoods Received & Outward Spinning Note: GRN-APX-4109\nInput Received: 9,920 KG De-fibered scrap\nProcessing Loss / Dust & Noil: 1,720 KG\nFinal Yarn Produced: 8,200 KG (Recovery: 82.66%)\nBatch Lot TX-000184 Confirmed Balanced.",
  },
];

export const FRAUD_DOCUMENTS: ExtractedDocumentData[] = [
  {
    id: "doc-fraud-01",
    documentType: "waste_invoice",
    fileName: "INV-2026-MANIP-1102_Declared_Waste.pdf",
    fileSize: "1.1 MB",
    uploadTimestamp: "2026-08-23T10:00:00Z",
    issuer: "Shree Textile Waste Traders, Surat",
    targetParty: "Apex Recycled Yarns Ltd",
    referenceNumber: "INV-SUR-1102",
    materialName: "Unsorted Mill Waste Cuttings",
    quantityKg: 10000,
    composition: {
      cottonPercentage: 60.0,
      polyesterPercentage: 40.0,
      fiberDescription: "Commercial Mixed Waste",
    },
    gsm: 180,
    source: "post-industrial",
    dispatchDate: "2026-08-23",
    location: "Surat, Gujarat",
    confidence: 0.92,
    extractedFields: {
      invoiceNumber: { value: "INV-SUR-1102", confidence: 0.98, label: "Invoice Number" },
      grossQuantity: { value: "10,000 kg", confidence: 0.96, label: "Input Batch Weight" },
      declaredCotton: { value: "60.0%", confidence: 0.91, label: "Supplier Declared Cotton" },
    },
    rawTextSnippet: "SHREE TEXTILE WASTE TRADERS\nInvoice: INV-SUR-1102\nMaterial: 10,000 KG Mixed Cotton Poly Scrap\nDeclared Ratio: 60% Cotton / 40% Polyester",
  },
  {
    id: "doc-fraud-02",
    documentType: "weighbridge_slip",
    fileName: "WB-SLIP-7731_Inbound_Slip.pdf",
    fileSize: "750 KB",
    uploadTimestamp: "2026-08-23T15:00:00Z",
    issuer: "Apex Spinning Inbound Gate",
    targetParty: "Apex Recycled Yarns Ltd",
    referenceNumber: "WB-APX-7731",
    materialName: "Waste Scrap Bales",
    quantityKg: 9950,
    composition: {
      cottonPercentage: 60.0,
      polyesterPercentage: 40.0,
      fiberDescription: "Inbound Waste Bales",
    },
    source: "post-industrial",
    receiveDate: "2026-08-23",
    location: "Erode Processing Gate",
    confidence: 0.96,
    extractedFields: {
      netReceived: { value: "9,950 kg", confidence: 0.99, label: "Weighed Inbound Quantity" },
    },
    rawTextSnippet: "APEX GATE 1 WEIGHBRIDGE\nSlip: WB-APX-7731\nInbound Gross: 21,950 KG | Tare: 12,000 KG | Net: 9,950 KG",
  },
  {
    id: "doc-fraud-03",
    documentType: "recycling_certificate",
    fileName: "Expired_GRS_Certificate_GRS-2024-9981.pdf",
    fileSize: "1.9 MB",
    uploadTimestamp: "2026-08-24T09:00:00Z",
    issuer: "Intertek Inspection Services",
    targetParty: "Apex Recycled Yarns Ltd",
    referenceNumber: "GRS-2024-9981-EXP",
    materialName: "Global Recycled Standard (GRS) Scope Certificate",
    quantityKg: 200000,
    composition: {
      cottonPercentage: 60.0,
      polyesterPercentage: 40.0,
      fiberDescription: "Recycled Yarn Scope",
    },
    source: "post-industrial",
    certification: {
      standard: "GRS",
      certificateNumber: "GRS-2024-9981-A",
      validFrom: "2024-01-01",
      validUntil: "2025-06-30",
      status: "Expired",
    },
    confidence: 0.98,
    extractedFields: {
      certStandard: { value: "GRS v4.0", confidence: 0.99, label: "Certification Standard" },
      certStatus: { value: "EXPIRED (Expired June 30, 2025)", confidence: 0.99, label: "Validity Status", isFlagged: true },
    },
    rawTextSnippet: "INTERTEK GRS CERTIFICATE\nCertificate: GRS-2024-9981-A\nLicensee: Apex Recycled Yarns Ltd\nValid Until: 30-JUN-2025 [DOCUMENT HAS EXPIRED 14 MONTHS AGO]",
  },
  {
    id: "doc-fraud-04",
    documentType: "grn",
    fileName: "GRN-MANIPULATED_12500KG_Claim.pdf",
    fileSize: "1.5 MB",
    uploadTimestamp: "2026-08-24T14:30:00Z",
    issuer: "Apex Recycled Yarns Ltd",
    targetParty: "Global FastFashion Retailer",
    referenceNumber: "GRN-CLAIM-990",
    materialName: "Claimed 100% Recycled Cotton Eco-Yarn",
    quantityKg: 12500,
    composition: {
      cottonPercentage: 95.0,
      polyesterPercentage: 5.0,
      fiberDescription: "Manipulated Claim: 12,500 KG Output from 10,000 KG Input",
    },
    gsm: 260,
    source: "post-industrial",
    dispatchDate: "2026-08-24",
    confidence: 0.95,
    extractedFields: {
      claimedOutput: { value: "12,500 kg", confidence: 0.99, label: "Claimed Recycled Yarn Output", isFlagged: true },
      claimedCotton: { value: "95.0% (Mismatches 60% Input Spec)", confidence: 0.96, label: "Claimed Fiber Blend", isFlagged: true },
      impliedRecovery: { value: "125.6% (Physically Impossible)", confidence: 0.99, label: "Implied Recovery Rate", isFlagged: true },
    },
    rawTextSnippet: "APEX RECYCLED YARNS LTD\nOutward Dispatch Note: GRN-CLAIM-990\nClaimed Output: 12,500.00 KG Recycled Spun Yarn\nBlend Claimed: 95% Recycled Cotton / 5% PET\n[ANOMALY: CLAIMED MASS EXCEEDS ALL INBOUND INPUT MATERIAL]",
  },
];

export const CLEAN_VCR_RECORD: VerifiedCircularityRecord = {
  vcrId: "TX-000184",
  batchId: "BATCH-2026-IND-8842",
  status: "VERIFIED",
  issueTimestamp: "2026-08-22T18:00:00Z",
  origin: "Sri Lakshmi Garment Mills, Tirupur, India",
  destinationBrand: "Nordic EcoWear Global",
  materialType: "Post-Industrial Cotton/Polyester Waste Blend",
  wasteDivertedKg: 10000,
  verifiedRecycledOutputKg: 8200,
  recycledContentPercentage: 92,
  chainOfCustodyStatus: "Verified",
  evidenceCompletenessPercent: 100,
  aiRiskScore: "Low",
  auditScoreNumeric: 98,
  verificationHash: "0x8f2a9e33b5c7714902d8471c99fa68a35e2194b17c938d2f09d841e21b8c1992",
  issuerSignature: "TexTrace-AI-VeriEngine-v2.4-RSA4096",
  esgImpact: {
    co2AvoidedKg: 21320,
    waterSavedLiters: 1980000,
    landfillDivertedKg: 10000,
    energySavedKwh: 15400,
  },
  ledger: {
    wasteGeneratedKg: 10000,
    transportLossKg: 80,
    recyclerReceivedKg: 9920,
    processingLossKg: 1720,
    recycledYarnProducedKg: 8200,
    recoveryRatePercent: 82.66,
    toleranceDeviationPercent: 0.12,
    massConservationDeltaKg: 0,
    isBalanced: true,
    notes: "Mass balance reconciled within 0.12% precision tolerance across 5 supply chain tiers.",
  },
  anomalies: [],
  nodes: [
    {
      id: "node-1",
      stage: 1,
      name: "Waste Generation & Segregation",
      entity: "Sri Lakshmi Garment Mills Ltd",
      location: "Tirupur, Tamil Nadu, India",
      action: "Cutting clip scrap collection & pre-consumer bale sorting",
      date: "2026-08-20",
      inputKg: 10000,
      outputKg: 10000,
      status: "verified",
      documents: ["INV-2026-8842", "Mill Spec Sheet"],
      icon: "Factory",
    },
    {
      id: "node-2",
      stage: 2,
      name: "Logistics & Inbound Receiving",
      entity: "Coimbatore Integrated Hub",
      location: "Coimbatore, India",
      action: "Transit tare/gross weighing and moisture stabilization",
      date: "2026-08-20",
      inputKg: 10000,
      outputKg: 9920,
      status: "verified",
      documents: ["WB-99014", "Transport Manifest"],
      icon: "Truck",
    },
    {
      id: "node-3",
      stage: 3,
      name: "Mechanical De-fibering & Recycling",
      entity: "EcoSpin Reclaimers Pvt Ltd",
      location: "Coimbatore, India",
      action: "RCS certified mechanical tearing, blending and garnetting",
      date: "2026-08-21",
      inputKg: 9920,
      outputKg: 9920,
      status: "verified",
      documents: ["CU-881920-RCS", "SGS-IND-7712-Q"],
      icon: "Cpu",
    },
    {
      id: "node-4",
      stage: 4,
      name: "Ring Spinning & Yarn Production",
      entity: "Apex Recycled Yarns Ltd",
      location: "Erode, Tamil Nadu, India",
      action: "Carding, drawing, roving and Ne 24s/1 ring yarn spinning",
      date: "2026-08-22",
      inputKg: 9920,
      outputKg: 8200,
      status: "verified",
      documents: ["GRN-APX-4109", "Yarn QA Sheet"],
      icon: "Layers",
    },
    {
      id: "node-5",
      stage: 5,
      name: "Garment Manufacturing & Distribution",
      entity: "Nordic EcoWear Global",
      location: "Stockholm, Sweden",
      action: "Circular circular jersey manufacturing & brand distribution",
      date: "2026-08-24",
      inputKg: 8200,
      outputKg: 8200,
      status: "verified",
      documents: ["DPP Digital Passport", "Brand Master Claim"],
      icon: "Shirt",
    },
  ],
  documents: CLEAN_DOCUMENTS,
};

export const DEMO_SCENARIOS: AuditScenario[] = [
  {
    id: "clean-indian-chain",
    name: "Scenario 1: Clean Indian Garment Supply Chain",
    badge: "100% Audit Pass",
    type: "clean_pass",
    description: "Tirupur cutting mill → Coimbatore mechanical recycler → Erode yarn spinner → Nordic EcoWear. Clean mass conservation, valid RCS certification, zero anomalies.",
    wasteOrigin: "Sri Lakshmi Garment Mills (Tirupur, India)",
    brand: "Nordic EcoWear Global",
    documents: CLEAN_DOCUMENTS,
    expectedResult: "PASS",
    anomaliesCount: 0,
  },
  {
    id: "fraud-manipulated-chain",
    name: "Scenario 2: Manipulated Mass & Expired Scope Fraud",
    badge: "3 Critical Anomalies Flagged",
    type: "fraud_fail",
    description: "Surat waste trader → Erode spinner. Input is 10,000 kg but claimed recycled output is 12,500 kg (violating mass conservation), GRS cert is 14 months expired, and cotton ratio was falsified.",
    wasteOrigin: "Shree Textile Waste Traders (Surat, India)",
    brand: "Global FastFashion Retailer",
    documents: FRAUD_DOCUMENTS,
    expectedResult: "FAIL",
    anomaliesCount: 3,
  },
  {
    id: "custom-sandbox-upload",
    name: "Scenario 3: Live Custom Document Upload Sandbox",
    badge: "Interactive AI Parser",
    type: "custom_upload",
    description: "Drag-and-drop your own mill invoices, lab test PDFs, or weighbridge slips. TexTrace AI parses unstructured evidence and recalculates mass balance in real-time.",
    wasteOrigin: "User Defined Facility",
    brand: "User Selected Partner",
    documents: [],
    expectedResult: "PASS",
    anomaliesCount: 0,
  },
];
